dist: xenial
language: python
cache: pip
python:
  - 2.7
  - 3.7

branches:
  only:
    - master
    - /^\d[\d.]+$/

install:
  - pip install -e .[test]

script:
  - make build

deploy:
  provider: pypi
  user: getsentry
  password:
    secure: k9zBwbKKu+26VDGIOMK4YV/4YaVl1fYzBqb7YLIIA9m5YO1koo97S4KYkvnSQ3keC3nBH6xLMe9m9VBVDp8rUYUBEBt0q/mbHuLV3gB+F55VJj1Sh9e5krEkTvQMaffnHdq9e9yu+j8wfIlC1LcbhmFXxtQY5qlV97ET28ikkOfEaO4XOfEphr3domZcxJ8/SqWDyW3F/6lWJYkQVcJL3vDcrwu8KqRjNeXcuBZLD79SLT4YecrRCpeOi5h6DZnwKiMPrx9PZ5lDhahqI3Cbe50KPTudtTleq8kcglC4ecbRX0lAAG7ra1mBsSCuqJZBh5WUnHnU4FxvVEY3+2wABmc1kSNc6P+gFlMU9URJtiB+CcGTpKdIbZO6ptT0iyFqaF38kdNk/KKbB+MAH+LhU+8kXK+Y+dGCzHZrvaEa6wsLm4fqYAUSp2fItZj2od3mEqbhwNHpTGD2h3P1xL2IgZziZYEIRmF/yRLfUSA7xWMBqHLsBM0LzQe1CC5fLKcMeoI/mapFm0ZDXqOazJq87KpliNLeBjC0I/+WMPI0RnvZ2gFEKUEaqA4zQVI7HRcjzM3Jo0D606VxPpa9QRLt+4qOaVwJqLe8QMuGho9Bd74qpnmZ+YUQfLQJb2vT8qn1tbHXActkUSqXEnEu+8EJAmK5UVIDui6U4qzdu4fTLws=
  distributions: "sdist bdist_wheel"
  on:
    tags: true

notifications:
  email:
    on_success: never
