name: build
on: push

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.6.14
          - 3.7.11
          - 3.8.11
          - 3.9.6
    steps:
    - uses: actions/checkout@v2

    - name: Install python
      uses: gabrielfalcao/pyenv-action@v8
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip  # upgrade pip after installing python

    - name: Install and run fmt + lint
      run: |
          pip install --disable-pip-version-check 'black==21.6b0' 'flake8==3.9.2'
          make fmt && make lint

    - name: Install and run tests
      run: |
          pip install --disable-pip-version-check -e .[tests]
          make test
