name: build
on: push

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.6.13
          - 3.7.9
          - 3.8.10
          - 3.9.2
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python }}"

    - name: Install and run fmt + lint
      run: |
          pip install --disable-pip-version-check 'pre-commit==2.18.1'
          make fmt

    - name: Install and run tests
      run: |
          pip install --disable-pip-version-check -e .[tests]
          make test
